description: "Updated UnDraw library. These illustrations are designed by Katerina Limpitsouni."
name: "ms_undraw"
repository: "https://github.com/Marcus-Software/ms_undraw"
version: "3.2.0"
dependencies: 
  flutter_svg: ">=1.0.0 <2.0.0"
  http: ">=0.13.1 <1.0.0"
  flutter: 
    sdk: "flutter"
dev_dependencies:
  cli_util: "^0.3.0"
  yaml: ^3.1.2
  fhir_yaml: ^0.9.0
  flutter_test: 
    sdk: "flutter"
environment:
  sdk: ">=3.0.0 <4.0.0"
flutter: null
